name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag milotodorovich/from-scratch:$(git rev-parse HEAD)
    - name: Run tests
      run: docker run --rm milotodorovich/from-scratch:$(git rev-parse HEAD) scripts/test
