name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag milotodorovich/from-scratch:{{commit_date 'YYYYMMDD-HHmmss' tz='America/Chicago'}}-{{sha}}
    - name: Run tests
      run: docker run --rm milotodorovich/from-scratch:{{commit_date 'YYYYMMDD-HHmmss' tz='America/Chicago'}}-{{sha}} scripts/test
